version: "3.8"

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=portfolio'
      - 'POSTGRES_PASSWORD=local'
      - 'POSTGRES_USER=local'
    ports:
      - '5432:5432'
