spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/portfolio
    username: {{db_username}}
    password: {{db_password}}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    com.barbzdev: info
    web: info

com:
  barbzdev:
    auth:
      usr: {{auth_username}}
      pwd: {{auth_password}}