spring:
  datasource:
    url: jdbc:postgresql://barbzdev.com:5432/portfolio
    username: {{db_username}}
    password: {{db_password}}
    driver-class-name: org.postgresql.Driver

# Configuration for nginx "proxy_set_header X-Forwarded-Prefix '/portfolio';"
# In order to fix 404 request of swagger when tries to retrieve /v3/api-docs
server:
  forward-headers-strategy: framework

logging:
  level:
    com.barbzdev: info
    web: info

com:
  barbzdev:
    auth:
      usr: {{auth_username}}
      pwd: {{auth_password}}