server:
  port: 8000

springdoc:
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui

logging:
  level:
    com.barbzdev: debug
    web: debug